INSERT INTO TEAM_DETAILS VALUES (1,'IS3987','VIGNESH','DEVELOPER','HDS','123');
INSERT INTO TEAM_DETAILS VALUES (2,'IS3988','Naveen','manager','HDS','123');
INSERT INTO TEAM_DETAILS VALUES (3,'IS3989','chandrasekar','DEVELOPER','HDS','123');

INSERT INTO TOPICS (ID, TITLE, ATTACHEMENT) VALUES (1,'CHAOS', null);


--INSERT INTO SCOREBOARD VALUES (1,1,1,10,1);

