CREATE TABLE `TEAM_MEMBER_DETAILS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`EMPID` VARCHAR(255) NOT NULL UNIQUE,
	`EMPNAME` VARCHAR(255) NOT NULL,
	`DESIGNATION` VARCHAR(255) NOT NULL,
	`TEAM_ID` INT,
	`BU` VARCHAR(255) NOT NULL,
	`EMAIL` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `TECHTALK_TEAMS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`TEAM_NAME` VARCHAR(255) NOT NULL,
	`VERSION_ID` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `TOPICS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`TITLE` varchar(255) NOT NULL,
	`ATTACHEMENT` blob,
	`PRESENTED_BY` INT NOT NULL,
	`PRESENTED_ON` DATE NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `RATINGS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`FEED1` INT,
	`FEED2` INT,
	`FEED3` INT,
	`FEED4` INT,
	`FEED5` INT,
	`FEED6` INT,
	`TOPIC_ID` INT NOT NULL,
	`TEAM_MEMBER_ID` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `VERSION` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`START_DATE` DATETIME NOT NULL,
	`END_DATE` DATETIME,
	`IS_CURRENT` BOOLEAN NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `USER` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`EMPID` VARCHAR(255) NOT NULL UNIQUE,
	`PASSWORD` VARCHAR(255) NOT NULL,
	`TEAM_MEMBER_ID` INT NOT NULL,
	`IS_ACTIVE` BOOLEAN NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `TEAM_MEMBER_DETAILS` ADD CONSTRAINT `TEAM_MEMBER_DETAILS_fk0` FOREIGN KEY (`TEAM_ID`) REFERENCES `TECHTALK_TEAMS`(`ID`);

ALTER TABLE `TECHTALK_TEAMS` ADD CONSTRAINT `TECHTALK_TEAMS_fk0` FOREIGN KEY (`VERSION_ID`) REFERENCES `VERSION`(`ID`);

ALTER TABLE `TOPICS` ADD CONSTRAINT `TOPICS_fk0` FOREIGN KEY (`PRESENTED_BY`) REFERENCES `TEAM_MEMBER_DETAILS`(`ID`);

ALTER TABLE `RATINGS` ADD CONSTRAINT `RATINGS_fk0` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPICS`(`ID`);

ALTER TABLE `RATINGS` ADD CONSTRAINT `RATINGS_fk1` FOREIGN KEY (`TEAM_MEMBER_ID`) REFERENCES `TEAM_MEMBER_DETAILS`(`ID`);

ALTER TABLE `USER` ADD CONSTRAINT `USER_fk0` FOREIGN KEY (`TEAM_MEMBER_ID`) REFERENCES `TEAM_MEMBER_DETAILS`(`ID`);
