CREATE TABLE `TEAM_DETAILS` (
	`ID1` INT NOT NULL AUTO_INCREMENT,
	`EMPID` VARCHAR(255) NOT NULL UNIQUE,
	`EMPNAME` VARCHAR(255) NOT NULL,
	`DESIGNATION` VARCHAR(255) NOT NULL,
	`TEAM_NAME` VARCHAR(255) NOT NULL,
	`BU` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID1`,`EMPID`)
);

CREATE TABLE `TECHTALK_TEAM1` (
	`ID2` INT NOT NULL AUTO_INCREMENT,
	`TEAM_NAME` VARCHAR(255) NOT NULL,
	`ID1` INT NOT NULL,
	PRIMARY KEY (`ID2`)
);

CREATE TABLE `TECHTALK_TEAM2` (
	`ID3` INT NOT NULL,
	`TEAM_NAME` VARCHAR(255) NOT NULL,
	`ID1` INT NOT NULL,
	PRIMARY KEY (`ID3`)
);

CREATE TABLE `TOPICS` (
	`ID` INT NOT NULL,
	`TITLE` VARCHAR(255) NOT NULL,
	`ATTACHEMENT` blob,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `SCOREBOARD` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`WEEK_NO` INT NOT NULL,
	`PRESENTER` INT NOT NULL,
	`SCORE` INT NOT NULL,
	`TOPIC_ID` INT NOT NULL
);

ALTER TABLE `TECHTALK_TEAM1` ADD CONSTRAINT `TECHTALK_TEAM1_fk0` FOREIGN KEY (`ID1`) REFERENCES `TEAM_DETAILS`(`ID1`);

ALTER TABLE `TECHTALK_TEAM2` ADD CONSTRAINT `TECHTALK_TEAM2_fk0` FOREIGN KEY (`ID1`) REFERENCES `TEAM_DETAILS`(`ID1`);

ALTER TABLE `SCOREBOARD` ADD CONSTRAINT `SCOREBOARD_fk0` FOREIGN KEY (`PRESENTER`) REFERENCES `TEAM_DETAILS`(`ID1`);

ALTER TABLE `SCOREBOARD` ADD CONSTRAINT `SCOREBOARD_fk1` FOREIGN KEY (`TOPIC_ID`) REFERENCES `TOPICS`(`ID`);
